---



- name: Replace line in file
  hosts: all
  become: true
  tasks:
    - name: pulling origional file
      fetch:
        src: "/etc/default/test_file"
        dest: "local_backup/{{ inventory_hostname }}-configfile"
        flat: no

    - name: editing line in default
      replace:
        path: /etc/default/test_file
        regexp: '\A((?:[^\r\n]*\r?\n){2})[^\r\n]*(\r?\n|$)'
        replace: '\1{{ edit1 }}\2'
        backup: true    # /tmp/testfile.txt
